package com.everis.bbd;

/**
 * Hello world! Autogenerated.
 *
 */
public class App 
{
    /**
     * Main class.
     * @param args program arguments.
     */
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
