#! /bin/bash

# Directories
DICTIONARIES_DIR=dictionaries/
DICTIONARIES_PATH=../config/$DICTIONARIES_DIR

# Dictionary names
CHAR_DICTIONARY_NAME=char
WORD_DICTIONARY_NAME=word
WORD_SUBS_DICTIONARY_NAME=words
DICTIONARY_BACKUP_SUFFIX=_bu
DICTIONARY_SUFFIX_NAME=.dictionary

