#! /bin/bash

# Directories
DICTIONARIES_DIR=dictionaries
DICTIONARIES_PATH=../config/$DICTIONARIES_DIR

# Dictionary names
CHAR_DICTIONARY_NAME=char
WORD_DICTIONARY_NAME=word
WORD_SUBS_DICTIONARY_NAME=words
DICTIONARY_BACKUP_SUFFIX=_bu
DICTIONARY_SUFFIX_NAME=.dictionary

# Creating dictionaries in case they don't exist.
touch $DICTIONARIES_PATH/$CHAR_DICTIONARY_NAME$DICTIONARY_SUFFIX_NAME
touch $DICTIONARIES_PATH/$WORD_DICTIONARY_NAME$DICTIONARY_SUFFIX_NAME
touch $DICTIONARIES_PATH/$WORD_SUBS_DICTIONARY_NAME$DICTIONARY_SUFFIX_NAME
